### ISSUE TITLE
GUI mode via Dear PyGUI

### ISSUE THREAD

**Issue by zuggamasta** [zuggamasta/midiTracker#30]
Dear PyGUI could be used to create and render a window. Also it could free up the keyboard only inputs.

https://github.com/hoffstadt/DearPyGui

**Comment by UmBsublime** [comment]
Hi, 
I'm new to midi/music in general, but the idea of a tracker in python was something I was looking into. Before starting my own TUI project I thankfully found your repo.
There is another TUI module in python called python-textual. A fresh new way to do gui in python (much simpler than curses) called [textual](https://textual.textualize.io/)
There is also some kind of overlap with GUI in general since it's also possible to use the same code to expose the app through a browser with [textual-web](https://github.com/Textualize/textual-web)

**Comment by zuggamasta** [comment]
Thank you for pointing to textual! I recently decide to keep the "no-ui" route for now. But in case I want to make the switch I have another tool at hand!
